In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [2]:
print(np.__version__)

1.26.4


In [4]:
arr1 = np.array((1, 2, 3, 4, 5))

print(arr1)

[1 2 3 4 5]


0-D Arrays

In [5]:
arr0 = np.array(42)

print(arr0)

42


# 1-D Arrays

In [8]:
arr1 = np.array((23, 45, 43, 42))

print(arr1)

[23 45 43 42]


# 2-D Arrays

In [10]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

print(arr2)

[[1 2 3]
 [4 5 6]]


# 3-D arrays

In [11]:
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr3)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


# Check Number of Dimensions?

In [12]:
print(arr3.ndim)

3


# Higher Dimensional Arrays

In [13]:
arr5 = np.array([1, 2, 3, 4], ndmin=5)

print(arr5)
print('number of dimensions :', arr5.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


# NumPy Array Indexing

In [14]:
print(arr5[0])

[[[[1 2 3 4]]]]


In [15]:
arra = np.array([1, 2, 3, 4])

print(arra[2] + arra[3])

7


# Access 2-D Arrays

In [16]:
arr2d = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr2d[0, 1])

2nd element on 1st row:  2


# Access 3-D Arrays

In [17]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr3d[0, 1, 2])

6


In [18]:
arr4 = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr4[1, -1])

Last element from 2nd dim:  10


# NumPy Array Slicing

In [19]:
arrs1 = np.array([1, 2, 3, 4, 5, 6, 7])

print(arrs1[1:5])

[2 3 4 5]


In [20]:
print(arrs1[4:])

[5 6 7]


In [21]:
print(arrs1[:4])

[1 2 3 4]


In [22]:
print(arrs1[-3:-1])

[5 6]


# STEP

In [23]:
print(arrs1[1:5:2])

[2 4]


In [24]:
print(arrs1[::2])

[1 3 5 7]


# Slicing 2-D Arrays

In [25]:
arrs2 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arrs2[1, 1:4])

[7 8 9]


In [26]:
print(arrs2[0:2, 2])

[3 8]


In [27]:
print(arrs2[0:2, 1:4])

[[2 3 4]
 [7 8 9]]
