# Data Types in NumPy

# Checking the Data Type of an Array

In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int32


In [3]:
arrs = np.array(['apple', 'banana', 'cherry'])

print(arrs.dtype)

<U6


In [4]:
arr1 = np.array([1, 2, 3, 4], dtype='S')

print(arr1)
print(arr1.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [5]:
arri = np.array([1, 2, 3, 4], dtype='i4')

print(arri)
print(arri.dtype)

[1 2 3 4]
int32


In [6]:
arrc = np.array(['a', '2', '3'], dtype='i')
print(arrc)

ValueError: invalid literal for int() with base 10: 'a'

# Converting Data Type on Existing Arrays

In [7]:
arras = np.array([1.1, 2.1, 3.1])

newarr = arras.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [8]:
newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True  True  True  True]
bool


In [9]:
newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3 4]
int32
